---
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name:      homeage-ingress
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home.k8s.stinnux.cloud`)
      kind: Rule
      services:
        - name: homepage-prod
          port: 3000
