apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie-prod
  namespace: argocd
spec:
  destination:
    namespace: mealie
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - repoURL: 'https://smarthall.github.io/helm-charts/'
    chart: mealie
    targetRevision: 0.0.10
    helm:
      valueFiles:
      - $values/charts/mealie/values.yml

  - repoURL: https://github.com/stinnux/argocd/
    targetRevision: HEAD
