apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage-prod
  namespace: argocd
spec:
  destination:
    namespace: homepage
    server: 'https://kubernetes.default.svc'

  project: default
  sources:
  - repoURL: 'https://jameswynn.github.io/helm-charts'
    chart: homepage
    targetRevision: 1.2.3
    helm:
      valueFiles:
      - $values/homepage/values.yml
  - repoURL: https://github.com/stinnux/argocd
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
