apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
spec:
  destination:
    namespace: postgres
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
  - repoURL: 'https://opensource.zalando.com/postgres-operator/charts/postgres-operator'
    chart: postgres-operator
    targetRevision: 1.12.2
    helm:
      valueFiles:
      - $values/postgres-operator/values.yml
  - repoURL: 'https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui'
    chart: postgres-operator-ui
    targetRevision: 1.12.2
    helm:
      valueFiles:
      - $values/postgres-operator/values-ui.yml

  - repoURL: https://github.com/stinnux/argocd
    targetRevision: HEAD
