apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  sources: 
    - repoURL: https://k8s-home-lab.github.io/helm-charts/
      targetRevision: 14.0.1
      chart: home-assistant
      helm:
        valueFiles:
        - $values/homeassistant/values.yml
    - repoURL: https://github.com/stinnux/argocd.git
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

